- name: Docker install and configuration
  hosts: _development
  become: true
  roles: 
    - dockerrole
- name: Postgre Database configuration
  hosts: _ansible_postgresql
  become: true
  roles:
    - postgresrole
- name: Nodejs server configuration
  hosts: _ansible_nodejs
  become: true
  roles:
    - noderole
- name: React UI Server configuration
  hosts: _ansible_react
  become: true
  roles:
    - reactrole