- name: configure postgre instance
  hosts: _ansible_postgresql
  become: true
  vars_files:
    -  secret.yml
  tasks:
    - name: upgrade all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: remove Older versions of Docker if installed
      ansible.builtin.dnf:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
          - podman
          - runc
        state: removed

    - name: install dnf-plugin
      ansible.builtin.dnf:
        name: dnf-plugins-core  ## important for adding additional repos like docker below I.E. dnf config-manager --add-repo https://download.docker.com
        state: latest

    - name: add docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/rhel/docker-ce.repo ## rhel the distro 
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: install docker
      ansible.builtin.package:
        name: docker-ce
        state: latest

    - name: add ec2-user to  docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker  ## adding docker to the corresponding group 
        append: yes
      #  sudo usermod -a -G docker ec2-user

    - name: start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: copy files to the postgresql node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/postgres/
        dest: /home/ec2-user/postgresql

    - name: remove cw_postgre container
      community.docker.docker_container:
        name: cw_postgre
        state: absent
        force_kill: true

    - name: remove clarusway/postgre image
      community.docker.docker_image:
        name: clarusway/postgre
        state: absent

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html
    - name: build container image
      community.docker.docker_image:
        name: clarusway/postgre
        build:
          path: /home/ec2-user/postgresql
        source: build
        state: present
      register: image_info

        # docker build -t clarusway/postgre ./home/ec2-user/postgresql

    - name: print the image_info
      ansible.builtin.debug:
        var: image_info

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
    - name: run docker postgresql container
      community.docker.docker_container:
        name: cw_postgre
        image: clarusway/postgre
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "{{ password }}"
        volumes:
          - /db-data:/var/lib/postgresql/data
      register: container_info

    - name: print the container info
      ansible.builtin.debug:
        var: container_info